export const DATA_SOURCE = "DATA_SOURCE";
export const USERS_REPOSITORY = "USERS_REPOSITORY";
export const EVENT_CATEGORY_REPOSITORY = "EVENT_CATEGORY_REPOSITORY";
export const NOTE_REPOSITORY = "NOTE_REPOSITORY";

export const SALT_ROUNDS = 10;
